[trial]
  name="TrialDataset"
  filename="trial_data.zip"
  url="http://web.eecs.umich.edu/~mihalcea/downloads/RealLifeDeceptionDetection.2016.zip"


  [trial.groups]
  	Deceptive=[ 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
  	            1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
  	            2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  	            2, 3, 4, 5, 6, 7, 8, 8, 8, 8,
  	            9,10,11,12,-1,13,13,13,13,-1,
  	           -1,14,-1,-1,-1,-1,15,16,-1,-1,
  	           -1]

  	Truthful= [17,18, 1, 1, 1, 1, 1,19,19,19,
  	           19,19,19,19,19,20,20,21,21,22,
  	           23,24,25,26,26, 6,27,28,29,30,
  	           29,30,31,31,32,32,33,34,35,36,
  	           -1,-1,37,38,39,40,41,42,43,44,
  	           45,46, 8, 2, 2, 2, 0, 0, 0, 8]
