service: lie-detector-ryan

frameworkVersion: ">=1.2.0 <2.0.0"

package:
  exclude:
    - "**"
  include:
    - ../lie_detector/models/**
    - ../lie_detector/networks/**
    - ../lie_detector/datasets/__init__.py
    - ../lie_detector/datasets/dataset.py
    - ../lie_detector/datasets/trial_dataset.py
    - ../lie_detector/datasets/dataset_sequence.py
    - ../lie_detector/__init__.py
    - ../lie_detector/predict.py
    - ../lie_detector/util.py
    - ../lie_detector/video_face_detector.py
    - ../__init__.py
    - server/app.py
provider:
  name: aws
  stage: dev1
  region: us-west-1
  runtime: python3.6
  memorysize: 3008
  timeout: 900
  versionFunctions: false

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-plugin-optimize
  
custom:
  optimize:
    disable: false
    exclude: "aws-sdk"
  wsgi:
    app: server.app.app
    packRequirements: false
  pythonRequirements:
    usePipenv: false
    dockerizePip: true
    slim: true
    strip: false
    slimPatterns:
      - "**/*.egg-info*"
      - "**/doc"
      - "**/tensorboard"
      - "**/tensorflow/contrib"
      - "**/tests"
    zip: true