service: lie-detector-ryan

frameworkVersion: ">=1.2.0 <2.0.0"

package:
  exclude:
    - "**/*"
  include:
    - ../lie_detector/models/**
    - ../lie_detector/networks/**
    - ../lie_detector/datasets/dataset.py
    - ../lie_detector/dataset_sequence.py
    - ../lie_detector/__init__.py
    - ../lie_detector/trial_dataset.py
    - ../lie_detector/predict.py
    - ../lie_detector/util.py
    - ../lie_detector/video_face_detector.py
    - server/app.py
provider:
  name: aws
  region: us-west-1
  runtime: python3.6
  memorysize: 3072
  timeout: 60
  versionFunctions: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-plugin-optimize
  
custom:
  wsgi:
    app: server.app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
    slim: true
    slimPatterns:
      - "**/*.egg-info*"
      - "**/doc"
      - "**/tensorboard"
      - "**/tensorflow/contrib"
      - "**/tests"
    strip: false
    zip: true